#!/usr/bin/perl

use strict;
use warnings;
use List::Permutor;

my %dist;
my @city;

for (<DATA>) {
    my ($city1, $city2, $dist) = /^(.*) to (.*) = (.*)$/;
    push (@city, $city1) unless $dist{$city1};
    push (@city, $city2) unless $dist{$city2};
    $dist{$city1}{$city2} = $dist;
    $dist{$city2}{$city1} = $dist;
}

my $p = List::Permutor->new( @city );

my $max = 0;

while ( my @list = $p->next ) {
   my $dist = total( @list );
   if ( $dist > $max ) {
        print "@list -> $dist\n";
        $max = $dist;
   }
}

sub total {
    my $t = 0;
    for my $i (0..(@_ - 2)) {
        $t += $dist{$_[$i]}{$_[$i+1]};
    }
    return $t;
}

__DATA__
Tristram to AlphaCentauri = 34
Tristram to Snowdin = 100
Tristram to Tambi = 63
Tristram to Faerun = 108
Tristram to Norrath = 111
Tristram to Straylight = 89
Tristram to Arbre = 132
AlphaCentauri to Snowdin = 4
AlphaCentauri to Tambi = 79
AlphaCentauri to Faerun = 44
AlphaCentauri to Norrath = 147
AlphaCentauri to Straylight = 133
AlphaCentauri to Arbre = 74
Snowdin to Tambi = 105
Snowdin to Faerun = 95
Snowdin to Norrath = 48
Snowdin to Straylight = 88
Snowdin to Arbre = 7
Tambi to Faerun = 68
Tambi to Norrath = 134
Tambi to Straylight = 107
Tambi to Arbre = 40
Faerun to Norrath = 11
Faerun to Straylight = 66
Faerun to Arbre = 144
Norrath to Straylight = 115
Norrath to Arbre = 135
Straylight to Arbre = 127
