#!/usr/bin/perl

use strict;
use warnings;

my %r;
my $time = $ARGV[0] || 2503;

while (<DATA>) {
    my ($name, $speed, $sprint, $rest) = /^(\S+) .* (\d+) km.* (\d+) seconds.* (\d+) seconds.$/;
    $r{$name}{speed} = $speed;
    $r{$name}{sprint} = $sprint;
    $r{$name}{rest} = $rest;
    $r{$name}{dist} = 0;
}

for my $sec (0...$time) {
    for my $name (keys %r) {
        $r{$name}{dist} += $r{$name}{speed} if ( $sec % ($r{$name}{sprint} + $r{$name}{rest}) < $r{$name}{sprint} );
    }
}

print "$_ : $r{$_}{dist}\n" for sort {$r{$a}{dist} <=> $r{$b}{dist}} keys %r;

__DATA__
Dancer can fly 27 km/s for 5 seconds, but then must rest for 132 seconds.
Cupid can fly 22 km/s for 2 seconds, but then must rest for 41 seconds.
Rudolph can fly 11 km/s for 5 seconds, but then must rest for 48 seconds.
Donner can fly 28 km/s for 5 seconds, but then must rest for 134 seconds.
Dasher can fly 4 km/s for 16 seconds, but then must rest for 55 seconds.
Blitzen can fly 14 km/s for 3 seconds, but then must rest for 38 seconds.
Prancer can fly 3 km/s for 21 seconds, but then must rest for 40 seconds.
Comet can fly 18 km/s for 6 seconds, but then must rest for 103 seconds.
Vixen can fly 18 km/s for 5 seconds, but then must rest for 84 seconds.
