#!/usr/bin/perl

use strict;
use warnings;

my %i;

while ( <DATA> ) {
    my ($i, $ca, $du, $fl, $te, $kc) = /^(.+): .*?(-?\d+).*?(-?\d+).*?(-?\d+).*?(-?\d+).*?(-?\d+)$/;
    $i{$i}{ca} = $ca;
    $i{$i}{du} = $du;
    $i{$i}{fl} = $fl;
    $i{$i}{te} = $te;
    $i{$i}{kc} = $kc;
}

my $max = 0;

for my $su (0..100) {
    for my $sp (0..(100 - $su)) {
        for my $ca (0..(100 - $su - $sp)) {
            for my $ch (0..(100 - $su - $sp - $ca)) {
                my $total = 1;
                for my $ing (qw( ca du fl te )) {
                    $total *= $su * $i{Sugar}{$ing} + 
                              $sp * $i{Sprinkles}{$ing} +
                              $ca * $i{Candy}{$ing} +
                              $ch * $i{Chocolate}{$ing};
                    last if $total <= 0;

                }
                if ($total > $max) {
                    $max = $total;
                    print "$max\n";
                }
            }
        }
    }
}

print "$max\n";

__DATA__
Sugar: capacity 3, durability 0, flavor 0, texture -3, calories 2
Sprinkles: capacity -3, durability 3, flavor 0, texture 0, calories 9
Candy: capacity -1, durability 0, flavor 4, texture 0, calories 1
Chocolate: capacity 0, durability 0, flavor -2, texture 2, calories 8
