#!/usr/bin/perl

use strict;
use warnings;

my @a = map( $_, <DATA> );
chomp @a;

my $target = $ARGV[0] || 150;
my $min = scalar @a;
my $count = 0;

for my $i (0..(2**scalar(@a)) - 1) {
    my $r = $i;
    my $bag = 0;
    my $a = 0;
    my $t = 0;
    while ($r) {
        if ($r % 2 == 1) {
            $bag += $a[$a] if $r % 2 == 1;
            $t++;
        }
        last if $bag > $target;
        $r >>= 1;
        $a++;
    }
    if ( $bag == $target ) {
        $count++ if $min == $t;
        if ( $t < $min ) {
            $min = $t;
            $count = 1;
        }
    }        
}

print "$count\n";

__DATA__
11
30
47
31
32
36
3
1
5
3
32
36
15
11
46
26
28
1
19
3
