#!/usr/bin/perl

use strict;
use warnings;

#You're airdropped near Easter Bunny Headquarters in a city somewhere. "Near", unfortunately, is as close as you can get - the instructions on the Easter Bunny Recruiting Document the Elves intercepted start here, and nobody had time to work them out further.
#
#The Document indicates that you should start at the given coordinates (where you just landed) and face North. Then, follow the provided sequence: either turn left (L) or right (R) 90 degrees, then walk forward the given number of blocks, ending at a new intersection.
#
#There's no time to follow such ridiculous instructions on foot, though, so you take a moment and work out the destination. Given that you can only walk on the street grid of the city, how far is the shortest path to the destination?
#
#For example:
#
#Following R2, L3 leaves you 2 blocks East and 3 blocks North, or 5 blocks away.
#R2, R2, R2 leaves you 2 blocks due South of your starting position, which is 2 blocks away.
#R5, L5, R5, R3 leaves you 12 blocks away.

#--- Part Two ---
#
#Then, you notice the instructions continue on the back of the Recruiting Document. Easter Bunny HQ is actually at the first location you visit twice.
#
#For example, if your instructions are R8, R4, R4, R8, the first location you visit twice is 4 blocks away, due East.
#
#How many blocks away is the first location you visit twice?

my ($ew, $ns, $dir) = (0, 0, 0);
my %seen = (0, 0);

my @inst = split( ", ", <DATA>);

for my $inst (@inst) {
  my ($turn, $dist) = $inst =~ /^(.)(.*)$/;
  if ($turn eq "R") {
    $dir++;
  } else {
    $dir--;
  }
  $dir %= 4;
  if ($dir == 0) {
    for (1..$dist) { 
      $ns++;
      if ($seen{"$ns,$ew"}) {
        print "Already been to $ns, $ew.\n";
      }
      $seen{"$ns,$ew"}++;
    }
  } elsif ($dir == 1) {
    for (1..$dist) { 
      $ew++;
      if ($seen{"$ns,$ew"}) {
        print "Already been to $ns, $ew.\n";
      }
      $seen{"$ns,$ew"}++;
    }
  } elsif ($dir == 2) {
    for (1..$dist) { 
      $ns--;
      if ($seen{"$ns,$ew"}) {
        print "Already been to $ns, $ew.\n";
      }
      $seen{"$ns,$ew"}++;
    }
  } else {
    for (1..$dist) { 
      $ew--;
      if ($seen{"$ns,$ew"}) {
        print "Already been to $ns, $ew.\n";
      }
      $seen{"$ns,$ew"}++;
    }
  }

}

my $answer = abs($ew) + abs($ns);
print "Ended up $answer blocks from home.\n";

__DATA__
R3, L5, R2, L1, L2, R5, L2, R2, L2, L2, L1, R2, L2, R4, R4, R1, L2, L3, R3, L1, R2, L2, L4, R4, R5, L3, R3, L3, L3, R4, R5, L3, R3, L5, L1, L2, R2, L1, R3, R1, L1, R187, L1, R2, R47, L5, L1, L2, R4, R3, L3, R3, R4, R1, R3, L1, L4, L1, R2, L1, R4, R5, L1, R77, L5, L4, R3, L2, R4, R5, R5, L2, L2, R2, R5, L2, R194, R5, L2, R4, L5, L4, L2, R5, L3, L2, L5, R5, R2, L3, R3, R1, L4, R2, L1, R5, L1, R5, L1, L1, R3, L1, R5, R2, R5, R5, L4, L5, L5, L5, R3, L2, L5, L4, R3, R1, R1, R4, L2, L4, R5, R5, R4, L2, L2, R5, R5, L5, L2, R4, R4, L4, R1, L3, R1, L1, L1, L1, L4, R5, R4, L4, L4, R5, R3, L2, L2, R3, R1, R4, L3, R1, L4, R3, L3, L2, R2, R2, R2, L1, L4, R3, R2, R2, L3, R2, L3, L2, R4, L2, R3, L4, R5, R4, R1, R5, R3
