#!/usr/bin/perl

use strict;
use warnings;

#The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#
#1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#
#Let us list the factors of the first seven triangle numbers:
#
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
#
# We can see that 28 is the first triangle number to have over five divisors.
#
# What is the value of the first triangle number to have over five hundred divisors?

sub factors {

    my $target = shift;
    my $total = 1;

    if ( $target % 2 == 0 ) {
        my $tmp = 1;
        while ( $target % 2 == 0 ) {
            $tmp++;
            $target /= 2;
        }
        $total = $tmp;
    }

    my $i = 3;
    while ( $i < sqrt($target) + 1 ) {
        my $tmp = 1;
        if ( $target % $i == 0 ) {
            my $tmp = 1;
            while ( $target % $i == 0 ) {
                $tmp++;
                $target /= $i;
            }
            $total *= $tmp;
        }
        $i += 2;
    }
    if ( $target > 1 ) {
        $total *= 2;
    }

    return $total;
} #sub factors



my $tri = 1;
my $index = 2;

while ( factors( $tri ) < 500 ) {
    $tri += $index;
    $index++;
}

print "$tri has " . &factors( $tri ) . " factors.\n";
