#!/usr/bin/perl

use strict;
use warnings;

#Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
#Pentagonal 	  	Pn=n(3n-1)/2 	  	1, 5, 12, 22, 35, ...
#Hexagonal 	  	Hn=n(2n-1) 	  	1, 6, 15, 28, 45, ...
#
#It can be verified that T285 = P165 = H143 = 40755.
#
#Find the next triangle number that is also pentagonal and hexagonal

sub is_tri {
  my $tmp = ( sqrt ( 8 * $_[0] + 1 ) - 1 ) / 2;
  return int( $tmp ) == $tmp ? 1 : 0;
}

sub is_pent {
  my $tmp = ( sqrt ( 24 * $_[0] + 1 ) + 1 ) / 6;
  return int( $tmp ) == $tmp ? 1 : 0;
}

my $i = 1;
my $hex;

while ( 1 ) {
  $hex = 2 * $i * $i - $i;
  last if is_tri( $hex ) && is_pent( $hex ) && $hex > 40755;
  $i++;
}

print "$hex\n";
